version: '3.8'

services:
  springboot_device_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_device_app
    ports:
      - "1213:1213"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db_devices
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  postgres:
    image: postgres:17
    container_name: postgres_container
    environment:
      POSTGRES_DB: db_devices
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"